### ISSUE TITLE
Private hosted GitLab path is wrong

### ISSUE THREAD

**Issue by aalasolutions** [mattermost/mattermost-plugin-gitlab#101]
Thanks for nice plugin.

I have integrated it with my self hosted git, it worked and gave me issues etc. 

New icons are added on the bottom left with proper count. But when I click on them it opens gitlab.com link instead of my self hosted URL.

**Comment by hanzei** [comment]
Would you please test if reloading solves your problem?

**Comment by aalasolutions** [comment]
Oh right,, it worked. Thanks
