### ISSUE TITLE
Still beta ? 

### ISSUE THREAD

**Issue by rgarrigue** [mattermost/mattermost-plugin-gitlab#104]
Hi

I read beta in the README and 1.0.0 is released. WHat's the status atm ? 

Best regard,

**Comment by hanzei** [comment]
cc @aaronrothschild

**Comment by aaronrothschild** [comment]
@rgarrigue I'll update the docs this week, sorry for the confusion.

**Comment by ericjaystevens** [comment]
Should we resolve the breaking change in [issue 67](https://github.com/mattermost/mattermost-plugin-gitlab/issues/67) first?

**Comment by hanzei** [comment]
@ericjaystevens I don't think it's worth breaking the plugin ID. It would mean, every admin would have to reconfigure the plugin and every user would have to re-connect.
