### ISSUE TITLE
Resolve error in make instructions

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-gitlab#107]
When trying to run the full make file I get the following error
```
Running errcheck
env GO111MODULE=off /usr/local/go/bin/go get github.com/kisielk/errcheck
errcheck ./server/... 
```
This should be resolved before we create a new release of the plugin.

**Comment by hanzei** [comment]
@DHaussermann Can you elaborate a bit? The log you posted doesn't show an error message. Maybe `errcheck` was still running?
