### ISSUE TITLE
How to subscribe to subgroups?

### ISSUE THREAD

**Issue by rugk** [mattermost/mattermost-plugin-gitlab#112]
I have a group called `group/subgroup/repo`, so a subgroup in a group.
But `/gitlab subscribe group/subgroup/repo` does not work and just returns `Unable to retreive informations`.

How can I do that?

**Comment by hanzei** [comment]
Subgroups are currently not supported. Please see https://github.com/mattermost/mattermost-plugin-gitlab/issues/65 for the ticket that tracks this.
