### ISSUE TITLE
GitLab Webhook not showing up in Mattermost

### ISSUE THREAD

**Issue by hardysim** [mattermost/mattermost-plugin-gitlab#121]
I've followed the instructions in the readme here, set up the plugin in mattermost, connected my user etc. I can see the gitlab-bar with the counters on mattermost correctly but it seems that no webhooks are showing up in mattermost when sent by gitlab.

I've created a webhook in a gitlab-project using `https://mattermost.my.domain/plugins/com.github.manland.mattermost-plugin-gitlab/webhook` and the secret created in the plugin settings page in mattermost. When testing, I get a green 200 OK result but I don't get any message in mattermost.

Where should the show up? In the private-messages-channel with the GitLab Plugin bot?

PS: Sending webhooks from gitlab to mattermost using the (now outdated?) Mattermost notifications project service works (but here I need to create an incoming webhook integration in mattermost which forwards the webhooks to a specific mattermost channel).

**Comment by levb** [comment]
@hardysim I don't use the plugin, but I _believe_ that you need to `/gitlab subscribe` to get the notifications posted into a channel. Did you do that?

**Comment by hardysim** [comment]
Hmm, so I need to set up the webhook for the project and each user needs to `/gitlab subscribe`?

---

When trying to subscribe, I receive an error. Using `/gitlab subscribe android` (`android` is a group on my GitLab server) results in:

> Unable to retreive informations for android/`

The same happens for `/gitlab subscribe android/project1` etc.. Any ideas?

**Comment by kop** [comment]
I also see some strange behaviour related to webhooks and I may have found the reason, but need an extra pair of eyes here, maybe I'm missing something.

@manland, please correct me if I'm wrong,

In https://github.com/mattermost/mattermost-plugin-gitlab/blob/master/server/plugin.go#L152

```go
p.API.KVSet(userID + GITLAB_IDUSERNAME_KEY, []byte(gitlabUsername) // userID is Mattermost user ID
```

But in https://github.com/mattermost/mattermost-plugin-gitlab/blob/master/server/plugin.go#L167

```go
p.API.KVGet(gitlabUserID + GITLAB_IDUSERNAME_KEY) // gitlabUserID is GitLab user ID
```

This mismatch makes `GITLAB_IDUSERNAME_KEY` useless and `ToUsers` will never be filled by webhooks.

**Comment by hardysim** [comment]
Just to make sure: How do I subscribe to projects or groups? Is `/gitlab subscribe android/project1` correct or do I need to do more? Maybe I missed something during the setup?

**Comment by kop** [comment]
@hardysim, If webhook(s) are already configured, then yes, `/gitlab subscribe android/project1` is all you need. Type `/gitlab help` for more commands.

**Comment by hardysim** [comment]
I've just activated "Enable Private Repositories" and now it's working. I can subscribe to my repo (it was set to private in gitlab so it's my fault).

---

But it seems like not all events are received. When sending all the test-events via gitlab (on the "edit webhook page") only a few are received in mattermost.

At gitlab, I see the "Recent Deliveries" are all green (200) but one (Confidential Issue Hook) which seems OK so far but only the following are received:

- Push events ✔️ 
- Tag push events ✔️
- Issue events ❌ 
- Confidential issues events ❌ 
- Note events ✔️
-Confidential notes events ❌ 
- Merge request events ❌ 
- Job events ❌ 
- Pipeline events ✔️
- Wiki pages events ❌ (but there's no wiki on the project so there's an error right in gitlab)

I checked all the triggers on the gitlab-webhook and added all the features with the subscribe command in mattermost:

`/gitlab subscribe android/project1 issues,merges,pushes,issue_comments,merge_request_comments,pipeline,tag,pull_reviews`

Is this a limit of the plugin? Or is there still something wrong?

**Comment by manland** [comment]
@kop wouhaou good catch! I create a dedicated issue now! Thank you very much ;)

@hardysim it's definitively not normal. I have tested (manually and with unit test) all events. But I haven't tested trigger them with the UI in settings. Maybe a field is empty or something like that... Can you look at logs please?

**Comment by hardysim** [comment]
Hmm, where do I find the logs? When I just "use" gitlab normally and check, which actions trigger messages in mattermost, it seems like the same issues are missing.

E.g. I create a new issue in gitlab but there's no message in mattermost. When I finish its MR and the pipeline is running, I get a message in mattermost (but still, only the pipeline for the merge-into-master, not the on-every-commit pipeline [which is fine for me]).

**Comment by hardysim** [comment]
I'v tested subscription by using gitlab (not via the tests on the webhook-details-page). When subscribing in mattermost, there are the following options:

- issues ✔️ 
- merges ✔️ 
- pushes ✔️ 
- issue_comments ✔️ 
- merge_request_comments ❌ 
- pipeline ✔️ 
- tag ✔️ 
- pull_reviews
  - could not test since using the free gitlab version
- label:"<labelname>"
  - not sure about this
  - will this react to issues / MR with the given label on them?
  - won't there already be a message when I subscribe to `merges` / `issues`?

**Comment by grisuthedragon** [comment]
I set up the plugin today and the same problem appears. I did every as described in the readme for an internally visible project and nothing gets recieved in the channel, where I subscribed the project. 
The test of the webhook replies with HTTP 200 sucht that it is at least recieved by the plugin properly. 

Is there any advance on this problem? Because we do not want to use the incomming webhook with the gitlab notifications since we need some projects in many channels.

I am using Mattermost 5.12 with the shippend Gitlab-Plugin ( Version 1.1  )

**Comment by cpaulik** [comment]
We are having problems getting private notifications for e.g. mentions or assignments. Is this related?

**Comment by grisuthedragon** [comment]
I figured out that the plugin actually works, but not with the Webhook-Test button in gitlab. After creating the webhook I clicked on the test button and checked several events and nothing happend. I created and issue and I got the message in mattermost. So it should be fixed, that the tests from gitlab work as well.

**Comment by raghavaggarwal2308** [comment]
@hardysim Are you still facing the issue or we can close it?

**Comment by hardysim** [comment]
Uh sorry, I'm no longer using either GitLab nor Mattermost so I don't know if its fixed in the mean time. Let's close this, yes.
