### ISSUE TITLE
Subscribe Success Message: Remind user about webhook setup needed

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-gitlab#130]
After setting up a subscription - users may not be aware or forget that they need to setup the webhook on their repo to point to MM.  

If the subscribe message made a note such as "Reminder: Setup a webhook from {repo_name} to point to `ServerURL/gitlabpath` for the subscription to work".  Optionally include a link to the instructions: https://github.com/mattermost/mattermost-plugin-gitlab#step-3-create-a-gitlab-webhook

This success message below kinda indicates everything is all ready to go - when it isn't and the user is confused why they aren't getting notifications:
![2020-01-09_04-16-43](https://user-images.githubusercontent.com/915956/72069292-b5d24f00-329b-11ea-95b6-b63365d53f26.png)

**Comment by manland** [comment]
Yes before #15 it's a very good idea! 

And if possible i'm for adding an option to display the url with private token. Because in my company not all user which use plugin have admin access and so can't add a webhook by their own.

**Comment by ericjaystevens** [comment]
I would like to work on this.

**Comment by gabrieljackson** [comment]
Thanks @ericjaystevens! Let us know if you need help with anything.

**Comment by ericjaystevens** [comment]
@manland My take on the private token is we should not display it, at least without the administrator explicitly configuring it to be shared. Some users may be using the secret to limit requests or using it in unexpected ways. I agree we need to make it more convenient, but we can achieve that with #15.

I love the idea of giving some useful guidance about the need to create a webhook after a success message. But there are a few scenarios when a webhook has been created before the subscription is created. A common example is if another team member setup up a subscription and webhook to the same project. For this reason, it makes sense to me to check for a webhook from that project and customize the message based on the result. This would prevent creating any confusion when our intention is to clear things up.

If a webhook exists, we keep the existing message.

> Successfully subscribed to UserName/ProjectName

If a webhook does not exist, in the project subscribed to. 

> Successfully subscribed to UserName/ProjectName. Please [setup a webHook]( http://gitLabURL/userName/ProjectName/-/settings/integrations ) to complete integration with your project. Additional instructions can be found [here](https://github.com/mattermost/mattermost-plugin-gitlab#step-3-create-a-gitlab-webhook)
