### ISSUE TITLE
When enabling the plugin, add a message to notify that it hasn't been configured properly

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-gitlab#138]
#### Summary 
The Gitlab plugin allows enabling even when the plugin is not configured with the OAuth client id, OAuth client secret and webhook secret which are essential for the plugin to work properly. However, enabling the plugin on the System Console > Plugin Management page, without any of those fields set up correctly doesn't give any indication of those requirements and says "This plugin is running"; whereas the server logs the error as 

`error: Must have a GitLab oauth client id","plugin_id":"com.github.manland.mattermost-plugin-gitlab"`

This behavior could be improved on this plugin to match the behavior in Github plugin that shows an error as soon as the enable button is clicked, as well as hide the `/gitlab` slash command until it's configured properly.

#### QA Steps
1. Install Gitlab plugin from Marketplace.
2. Make sure the plugin is not configured in the plugin's settings page.
3. Go to System Console > Plugin Management.
4. Enable the plugin.
5. Go to a channel and type `/gitlab`.

Expected: 
Step 4: A message/warning indicating that the plugin hasn't been configured.
Step 5: No slash command for gitlab shows up in the list.

#### Original Ticket
https://mattermost.atlassian.net/browse/MM-22209

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: GitLab" community channel](https://community.mattermost.com/core/channels/plugin-gitlab).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by attilamolnar** [comment]
Hi, I'll implement this

**Comment by jfrerich** [comment]
Thank you, @attilamolnar!
