### ISSUE TITLE
Filter issue_comments by label

### ISSUE THREAD

**Issue by ffuentes** [mattermost/mattermost-plugin-gitlab#144]
### Feature request

Display content related to *label* subscriptions only. Now when someone subscribe a repo by filtering issues by label, every comments get published even if the issues haven't the *label*.

For example I subscribe a repo like this:

```
/gitlab subcribe owner/repo issues,issue_comments,label:"doing"
```

I would espect that only issues created and closed with the label *doing* will be notified, including comments. But, every comment from all issues get notified.

### Sugestions

Maybe is as simple as adding:
```
if sub.Label() != "" && !containsLabel(event.Labels, sub.Label()) {
				continue
			}
```

in server/webhook/note.go will solve it.

**Comment by haardikdharma10** [comment]
Hey @iomodo, I'd love to trigger this issue and fix it. I went through the note.go file but ain't pretty sure where the code should be added. Can you help me out with the function and line number? Thanks :)

**Comment by iomodo** [comment]
@haardikdharma10 correct, that 's exactly the function. This would be the line where filter can go https://github.com/mattermost/mattermost-plugin-gitlab/blob/881e6321d2d8b4c509f55958d31e9ea246af71f8/server/webhook/note.go#L70

Let me know if you need anything
