### ISSUE TITLE
Subscriptions don't work - subscribes fine but doesn't post anything after that?

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [mattermost/mattermost-plugin-gitlab#146]
We're using:

>GitLab Community Edition 12.5.0 
>Mattermost Version 5.20.
>GitLab Plugin Version 1.1.0

I've set it up with an account just fine, have registered the application, etc. I invited the gitlab account to the team and channel. Then done:

    /gitlab subscribe whatever-group/thisthat pushes,issues,issue_comments

Which is successful, if I enter an invalid repository then it errors, so it's definitely connected. But whenever a new push/issue/comment is made nothing happens. It just sits there and carries on like normal.

**Comment by ericjaystevens** [comment]
@CaerphillyMediaLtd did you create and test a project hook in GitLab?

https://github.com/mattermost/mattermost-plugin-gitlab#step-3-create-a-gitlab-webhook

**Comment by gvcgael** [comment]
I have exactly the same problem.

> Gitlab Enterprise Edition 12.7.2-ee
> Mattermost version 5.21.0
> Gitlab plugin version 1.1.0

I'm using a Group webhook (One webhook for all the subgroups and subprojects).
When I use test the `push tag event`, the bot correctly notify about the tag in the channel.

When I tag one of my repo, its doesnt display anything in channel.

**Comment by gvcgael** [comment]
After some deeper testing, this plugin is only compatible with project hooks, not group hooks.

**Comment by aaronrothschild** [comment]
Follow up: Is there a release coming out for Gitlab that has Group Webhooks for non-ee edition?

**Comment by iomodo** [comment]
@CaerphillyMediaLtd @gvcgael if you are the author of the event you will not be notified. Is it the case?

**Comment by paulkitt** [comment]
Same problem here! Pretty sure I configured everything right.
Created a gitlab user with owner right in our gitlab group and connected the plugin as OAuth application. Then added the webhooks with that user. Displayed now as Project Hooks:
```
https://mattermost.bla.blub/plugins/com.github.manland.mattermost-plugin-gitlab/webhook
Issues Events Note Events Confidential Note Events Merge Requests Events Wiki Page Events 
SSL Verification: enabled

```
Then I connect with my normal mattermost acc my normal gitlab accout and subscribe in seperate channel `/gitlab subscribe https://gitlab.com/bla/services/blub issues,merges,issue_comments,merge_request_comments,pull_reviews`

When I fire test webhook in Gitlab I get `Hook executed successfully: HTTP 200` but in mattermost nothing happens.

**Comment by DHaussermann** [comment]
@CaerphillyMediaLtd let me know if this is still an issue. Just to add some info here for clarity:
- It is possible to save a subscription without actually having a webhook in place to deliver the events. Make sure there is a webhook to deliver from the target protect  
- If the webhook was successfully created, you can test the webhook from GitLab side to collect more info

**Comment by unode** [comment]
> Follow up: Is there a release coming out for Gitlab that has Group Webhooks for non-ee edition?

I think this is the reason why we are seeing the following when registering a webhook for a group project:

```
/gitlab webhook add grp-act/act-repo

POST https://gitlab.localdomain.com/api/v4/projects/3464/hooks: 422 {error: Invalid url given} (Only visible to you)
```

**Comment by raghavaggarwal2308** [comment]
@CaerphillyMediaLtd Are you still facing the issue or we can close it?
