### ISSUE TITLE
Add webhook without leaving mattermost

### ISSUE THREAD

**Issue by manland** [mattermost/mattermost-plugin-gitlab#15]
As a user (before I dev this plugin) I didn't know how to add a project to listen to in github-plugin. I didn't read the readme... meaculpa. But I think to be more easy to use we should add webhook for user. Like that user just `/gitlab subscribe owner/project` and all the magic make the job.

Obviously for group, we need to fetch all projects and add it to every repos. If user create a new project after this init step we will miss it... maybe we can cron a synchronizer... 

https://docs.gitlab.com/ce/api/projects.html#add-project-hook

**Comment by ericjaystevens** [comment]
I'll take this.

**Comment by manland** [comment]
@ericjaystevens I have started the Dev in #53 but I'm blocking because of missing feature in gitlab (API to add webhook for group). A contributor has started to work on it last week at gitlab... Wait and see!

**Comment by manland** [comment]
@ericjaystevens yes IMHO it's a good addition and with #36 it's a perfect fit for user to discover what is in sync and what not! I'm sorry I haven't time to do it (baby come 😅). If you want to continue #53 you are more than welcome!
