### ISSUE TITLE
clarify how average user can use plugin without access to webhook secret

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-plugin-gitlab#156]
https://github.com/mattermost/mattermost-plugin-gitlab#step-3-create-a-gitlab-webhook makes it sound like you must add webhook and secret to every single GitLab project you care about. How is an admin supposed to enable this plugin and expect hundreds of users to use it with various GitLab projects the admin doesn't even know about?

**Comment by manland** [comment]
Yes we agree on that and we work on a fix #137 thanks to @ericjaystevens ;)
