### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by wbaeck** [mattermost/mattermost-plugin-gitlab#157]
Hi

We are running Mattermost 5.21 and want to use the gitlab plugin. I followed all the steps from the readme and I'm able to have the Gitlab icon show up in Mattermost. When I click on it the authorization confirmation pops up. After selecting the "Autorize" button I get the following error message:
`Post https://{gitlab-server-url}/oauth/token: proxyconnect tcp: EOF`

I tried all different ways but just can't find a solution or at least a way to identify the issue. Checked the debug log of MM - but no other entries found there.

Please help me to solve this!

Thanks in advance

**Comment by amyblais** [comment]
FYI @manland or @iomodo

**Comment by manland** [comment]
No sorry I have no idea what the issue is :'( Maybe ask to github plugin developers because lot of code here is a fork from github-plugin? Or maybe a network people from MM?

**Comment by wbaeck** [comment]
Thanks for your quick reply. Will check at github-plugin!

**Comment by wbaeck** [comment]
Finally I was able to solve this issue. 

It was a config issue. Because we configured an outbound proxy to access the Marketplace we had to exclude our internal gitlab server from this with "NO_PROXY" according to https://docs.mattermost.com/install/outbound-proxy.html.

But thanks for reply.
