### ISSUE TITLE
Assignment list only contains issues that I've created myself

### ISSUE THREAD

**Issue by jurgenhaas** [mattermost/mattermost-plugin-gitlab#159]
From all the assigned issues to myself, the plugin only lists those that I also created myself. All those that have been created by other GitLab users and later being assigned to myself, are not included in the list.

Please let me know if you needed more information to reproduce this, but the effect is just exactly so without any exception.

**Comment by apollo13** [comment]
Could this be solely due to https://github.com/mattermost/mattermost-plugin-gitlab/blob/ceb5df141b6ad9cc22c47466111953dfc47af139/server/gitlab/api.go#L282 ? Ie Dropping the state should fix it?

**Comment by apollo13** [comment]
I stand corrected, it was the scope that default to `created_by_me` instead of `all`. Attached a PR that fixes it.
