### ISSUE TITLE
Question: Is it possible to subscribe issues related events to a separate channel?

### ISSUE THREAD

**Issue by medexdev** [mattermost/mattermost-plugin-gitlab#162]
Similar to Gitlab Mattermost service (from Gitlab), is it possible to customize which events are posted to which channels in mattermost? I'd like to have a separate channel for issues. Currently, all notifications come in gitlab channel.

**Comment by octoquad** [comment]
It is possible. If you create an Issues channel you can then subscribe the projects in that channel with
`/gitlab subscribe namespace/repo issues` or `/gitlab subscribe namespace issues` for all projects under the namespace (requires the latest version of the plugin). The default is issues, merge requests (merges), and tags. 

Naturally all projects need the webhook setup correctly. See [step 3](https://github.com/mattermost/mattermost-plugin-gitlab#step-3-create-a-gitlab-webhook) of the guide.

**Comment by mickmister** [comment]
Hi @medexdev, thanks for submitting this ticket. Does the explanation above solve your issue? I'll close the ticket for now. Let me know if you have any questions.
