### ISSUE TITLE
White space is missing before "view commit"

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-gitlab#163]
White space is missing before "view comment". This happens for several events including commits and pushes. 
I believe this may be a regression from the current release. A change was put in to to fix "View Commit" for multiple lines of text.
![GitlabViewComment](https://user-images.githubusercontent.com/35588783/80146255-9841a080-857f-11ea-9fba-c5f51dd4240e.PNG)

**Comment by octoquad** [comment]
Hmm, that's quite interesting. It's actually suppose to be a newline according to https://github.com/mattermost/mattermost-plugin-gitlab/blob/8e4f5a9e51d2e2534b7456cec856bfd8bea9766b/server/webhook/push.go#L56. 

Makes sense the test passed, I think a double space or backslash actually needs to replace the `\n` for the correct markdown syntax for a newline/HTML br tag.
