### ISSUE TITLE
Remove reference to community channel

### ISSUE THREAD

**Issue by thmo** [mattermost/mattermost-plugin-gitlab#168]
The channel mentioned at the bottom of the `README.md` is not valid anymore.

First, the correct address is `https://community.mattermost.com/core/channels/gitlab-plugin`, but second, that channel has been archived in the meantime.

**Comment by jasonblais** [comment]
@thmo actually, the channel does still exist, but you are correct that it's incorrect in the README.

The new channel exists at https://community.mattermost.com/core/channels/plugin-gitlab :) 

Submitted #169 to fix, good catch!
