### ISSUE TITLE
Add slash command autocomplete functionality

### ISSUE THREAD

**Issue by iomodo** [mattermost/mattermost-plugin-gitlab#175]
From 5.24 MM server has a slash command autocomplete functionality feature. An API can be found [here](https://github.com/mattermost/mattermost-server/blob/master/model/command_autocomplete.go#L28)
To implement the feature add `AutocompleteData` struct to the `Command` when registering a slash command.

Similar PRs:
For Todo plugin https://github.com/mattermost/mattermost-plugin-todo/pull/69
For Agenda plugin https://github.com/mattermost/mattermost-plugin-agenda/pull/40

**Comment by ericjaystevens** [comment]
I would like to work on this.
