### ISSUE TITLE
Plugin not working in subpath ( domain.org/mattermost/ )

### ISSUE THREAD

**Issue by mozzieongit** [mattermost/mattermost-plugin-gitlab#176]
Hi, 
I have mattermost installed in a subpath {domain}/mattermost/
When I click on the "connect to your Gitlab" icon I'm sent to 
`{domain}/plugins/com.github.manland.mattermost-plugin-gitlab/oauth/connect` 
instead of 
`{domain}/mattermost/plugins/com.github.manland.mattermost-plugin-gitlab/oauth/connect`

**Comment by mickmister** [comment]
@mozzieongit Thanks for reporting this. The linked PR should solve this issue.
