### ISSUE TITLE
Registration URL in README.md

### ISSUE THREAD

**Issue by thmo** [mattermost/mattermost-plugin-gitlab#181]
The `README.md` suggest to use `https://gitlab.com/profile/applications` or `https://gitlab.yourdomain.com/profile/applications` to register the plugin as an OAuth2 application.

Wouldn't it be better to suggest `https://gitlab.yourdomain.com/admin/applications`, in order to register the plugin globally for a self-hosted gitlab instance?

**Comment by hanzei** [comment]
If a Mattermost installation is coupled to `https://gitlab.com`,  `https://gitlab.com/profile/applications` is the place to go to register an OAuth2 app.

But maybe I'm misunderstanding the suggestion.

**Comment by thmo** [comment]
Actually, there are two cases:
1. usage of `gitlab.com`;
2. self-hosted Gitlab, on `gitlab.yourdomain.com`.

For (1), `https://gitlab.com/profile/applications` is correct.

For (2), I am proposing the `README.md` should suggest `https://gitlab.yourdomain.com/admin/applications` instead of `https://gitlab.yourdomain.com/profile/applications`, i.e., registering Mattermost as an OAuth2 app _for all users_ instead of for the _current_ one.

Hope this makes it clearer now.

**Comment by hanzei** [comment]
Got it :+1: To me that makes sense. @iomodo What do you think?

**Comment by gfairchild** [comment]
This would be great! As an admin of a self-hosted GitLab instance, I wasn't sure, but this issue confirms that `/admin/applications` is the appropriate place rather than `/profile/applications`.
