### ISSUE TITLE
Root/Master Webhook

### ISSUE THREAD

**Issue by DavidBusey** [mattermost/mattermost-plugin-gitlab#183]
label:type/question

#https://github.com/mattermost/mattermost-plugin-gitlab#step-4-subscribe-to-projects-and-groups

> Note for each project you want to receive notifications for or subscribe to, you must create a webhook

If I have multiple repos under one folder, is it possible to use a Gitlab webhook on a higher level so that I do not have to subscribe to each one?

For example:
`Code/ProjectA/[repo]`
`Code/ProjectB/[repo]`

Could I simply use the one webhook for `code/` to get both repos or do I have to create webhooks for each?

**Comment by mickmister** [comment]
@DavidBusey Does your request fall under the scope of this ticket? https://github.com/mattermost/mattermost-plugin-gitlab/issues/128

**Comment by DavidBusey** [comment]
> @DavidBusey Does your request fall under the scope of this ticket? #128

I did not see that ticket - seems that it does. Thanks!
