### ISSUE TITLE
Push event notifications contain broken link to Gitlab user page

### ISSUE THREAD

**Issue by n-st** [mattermost/mattermost-plugin-gitlab#184]
When commits are pushed to a repo, the plugin generates a message of the format "[Jane Doe](https://gitlab.example.com/Jane Doe) has pushed 1 commit to [janedoe/some-repo](https://gitlab.example.com/janedoe/some-repo)".

The link to the user's page is based on their *display name*, not *username*, and is therefore often invalid (404 on the Gitlab side of things).

**Comment by n-st** [comment]
From a quick look at the code it looks like this stems from a confusion about the Gitlab API:
- The notification text is assembled in [server/webhook/push.go, line 55](https://github.com/mattermost/mattermost-plugin-gitlab/blob/master/server/webhook/push.go#L55),
- based on `senderGitlabUsername`,
- [obtained from `event.UserName` from a `gitlab.PushEvent` argument](https://github.com/mattermost/mattermost-plugin-gitlab/blob/master/server/webhook/push.go#L41),
- which, in turn, is a wrapper around the ["user_name"](https://github.com/xanzy/go-gitlab/blob/master/event_webhook_types.go#L37) attribute in [Gitlab's webhook JSON format](https://docs.gitlab.com/ce/user/project/integrations/webhooks.html#push-events).

The actual username (as it would appear in the URL) is aptly named `UserUsername` in the `go-gitlab` library.

**Comment by n-st** [comment]
It seems that `event.UserName` is also used (perhaps accidentally) in `server/webhook.go` and `server/webhook/tag.go`.

I'd rather not set up a full Go development environment for such a small change, but perhaps this patch will be useful. :)
[0001-Fix-Use-Gitlab-username-instead-of-display-name-to-c.patch.txt](https://github.com/mattermost/mattermost-plugin-gitlab/files/4853654/0001-Fix-Use-Gitlab-username-instead-of-display-name-to-c.patch.txt)

**Comment by n-thumann** [comment]
I´d like to work on it, if you don´t mind 😊
