### ISSUE TITLE
Don't send reminders if there's nothing to be reminded of

### ISSUE THREAD

**Issue by svelle** [mattermost/mattermost-plugin-gitlab#185]
This:

```
GitLab Plugin BOT 11:22

Unread Messages
You don't have any unread messages.

Review Requests
You don't have any merge requests awaiting your review.

Assignments
You don't have any issues awaiting your dev.

Your Open Merge Requests
You don't have any open merge requests.
```

is annoying, we should not send these reminders if there's no useful info in it.

**Comment by svelle** [comment]
This should be a relatively simple fix.
Seems to be this function: https://github.com/mattermost/mattermost-plugin-gitlab/blob/e5d1e897dd562c4911ae707bbbe45b36591f775e/server/plugin.go#L253

**Comment by DigasNikas** [comment]
Greetings,
Can I lend a hand on this one?
