### ISSUE TITLE
Use SiteURL for all calls from the webapp

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-gitlab#188]
If the server's SiteURL is configured with a subpath, the webapp's API calls do not work. The task here is to make this plugin's client to prefix its URLs with the SiteURL.

Here's an example of how the SiteURL may be computed:
https://github.com/mattermost/mattermost-plugin-jira/blob/19a9c2442817132b4eee5c77e259b80a40188a6a/webapp/src/selectors/index.js#L13-L26

**Comment by khushijindal** [comment]
@mickmister I didn't understand what needs to be done here. I checked the given link and everything seems ok. Can you please elaborate?

**Comment by mickmister** [comment]
@khushijindal The link is to a [different project](https://github.com/mattermost/mattermost-plugin-jira), just to show how to get the SiteURL. This fix needs to be applied to other plugin projects as well, such as the GitLab plugin here. The SiteURL is currently not being used in the frontend portion of the GitLab plugin.

Does this make it more clear?

**Comment by mickmister** [comment]
Closing per https://github.com/mattermost/mattermost-plugin-gitlab/pull/177
