### ISSUE TITLE
Closing issues or merge requests does not create an event post with a link back to the project

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-gitlab#194]
When closing an issue or merge request, when the event is delivered rather then a link to the the project, the post will include text `[dhaussermann/dkh-project3]`  

![RepoLink](https://user-images.githubusercontent.com/35588783/90069234-068da880-dcc0-11ea-8d76-e62c60bed98c.PNG)

This issue is not new. I have just noticed that these events seem to differ from several other events where a proper link is included. 

These posts should match the new issue and new pull requests event (shown above) with a proper link.

**Comment by carantunes** [comment]
Hey! Can I take this one?

**Comment by hanzei** [comment]
Hey @carantunes,

Thanks for you high interest in the Mattermost project. We encourage new community members just pick up one or two issues when freshly stating with contributing to Mattermost. Would you mind waiting until you submitted your first PR before picking up this issue?
