### ISSUE TITLE
Re-opening an issue does not deliver an event

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-gitlab#195]
It would be ideal if re-opening an issue in GitLab would deliver an event. Currently creating or closing an issue delivers an event but, re-opening one does not. 

Steps:
- Create a subscription to a project that includes the `issues` feature
- Create a webhook to deliver the events that includes the `Issues Events` trigger
- Note that creating and closing issues delivers events to the target channel

Observed: Re-opening a closed issue is not a event that gets delivered.

**Comment by hanzei** [comment]
See https://github.com/mattermost/mattermost-plugin-github/issues/267 for a similar ticket
