### ISSUE TITLE
Webhook creation could show non-clickable version of the link 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-gitlab#196]
When you create a webhook via slash command, the address that GitLab uses for the webhook is shown in the confirmation post. This is displayed as a clickable link which may be a bit confusing for people. Even though the link is correct, attempting to follow it will result in a 401 response and the text `not authorized` . 

It may make more sense to show the link as a commented line of text `https://dkh-local.ngrok.io/plugins/com.github.manland.mattermost-plugin-gitlab/webhook` rather than the clickable link https://dkh-local.ngrok.io/plugins/com.github.manland.mattermost-plugin-gitlab/webhook

Steps:
- Subscribe to a project
- Using the slash command, add a webhook to deliver the evsent

**Observed**: 
A. Confirmation post shows a list of events and a clickable link such as https://dkh-local.ngrok.io/plugins/com.github.manland.mattermost-plugin-gitlab/webhook
B. Clicking the link results in 401

**Comment by kosgrz** [comment]
I will do it :)
