### ISSUE TITLE
webhook add fails on sub-groups

### ISSUE THREAD

**Issue by storrgie** [mattermost/mattermost-plugin-gitlab#200]
Just consumed 1.2.0, `/gitlab webhook add <group/project>` seems to work, however it seems to fail on anything involving sub-groups: `/gitlab webhook add <group/sub-group/project>`.

**Comment by hanzei** [comment]
@ericjaystevens you are going to work on this, right?

**Comment by ericjaystevens** [comment]
@hanzei  I had to scope out the issue before I committed but yes, I'll take this. It should be a quick fix, no upstream changes required.
