### ISSUE TITLE
Add command to run a new CI Build

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-gitlab#213]
Many customers are ocnsidering gitlab to replace Jenkins for Ci builds.  But we don’t have a way to let users trigger a new build in the Gitlab projects.  This ticket is a request to add a slash command such as `/gitlab build <project>` to kick-off a build.  After the build is complete, the user should be sent a message in the channel they initiated the command from with a link to the artifact/build output.

**Comment by tw-ayush** [comment]
is there an GitLab api that you can link here?

**Comment by hanzei** [comment]
https://docs.gitlab.com/ee/api/pipelines.html#create-a-new-pipeline seems like the right one to use

**Comment by tw-ayush** [comment]
Cool, thanks I'll have a look at it and reach back to you in case of doubt.

**Comment by hanzei** [comment]
Awesome, thanks for taking a look :+1:

**Comment by tw-ayush** [comment]
@hanzei @aaronrothschild based on the issue discerption i believe [this](https://docs.gitlab.com/ee/ci/triggers/#triggering-a-pipeline) to be more suitable. The other api seems more like a process to set-up a new pipeline (though i don't see any mention of how one will send the pipeline tasks in it). Please have a look and let me know about what you think.

**Comment by tw-ayush** [comment]
> @hanzei @aaronrothschild based on the issue discerption i believe [this](https://docs.gitlab.com/ee/ci/triggers/#triggering-a-pipeline) to be more suitable. The other api seems more like a process to set-up a new pipeline (though i don't see any mention of how one will send the pipeline tasks in it). Please have a look and let me know about what you think.

never mind I read through the lib.. seems-like the one you sent is good 👍

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-gitlab/pull/302
