### ISSUE TITLE
Command responses don't get posted in the RHS

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-gitlab#217]
Running a slash command in the RHS should post the response there.

See https://github.com/mattermost/mattermost-plugin-github/issues/364 for a similar bug.

**Comment by khushijindal** [comment]
Hey @hanzei ! Can I work on this issue? I am new to open source, so can you elaborate as to what needs to be done.

**Comment by hanzei** [comment]
Sorry for the late reply @khushijindal. It looks like you found the solution yourself :+1:
