### ISSUE TITLE
multiple GitLab instances

### ISSUE THREAD

**Issue by swills** [mattermost/mattermost-plugin-gitlab#242]
Is there a way to connect to multiple GitLab instances? I use both a personal one and the gitlab.com one and would like to connect the plugin to both.

**Comment by iomodo** [comment]
There is no way yet.

**Comment by hanzei** [comment]
Duplicate of

**Comment by cforce** [comment]
Is this feature request rejected, or why are all related tickets closed?
Confused about Duplicate of https://github.com/mattermost/mattermost-plugin-gitlab/issues/242, which is the same issue!?

**Comment by hanzei** [comment]
Good catch. 

The correct ticket to link is #35
