### ISSUE TITLE
Remove or convert HTML from issue/merge request description

### ISSUE THREAD

**Issue by caugner** [mattermost/mattermost-plugin-gitlab#249]
## Background

* We use the Mattermost GitLab bot to be informed about new issues and merge requests in our dev channel.
* We use [dependabot-gitlab]8https://gitlab.com/dependabot-gitlab/) to update our dependencies, and it automatically creates merge requests with a lot of HTML in the description.

## Problem

* Dependabot's merge requests contain a lot of HTML.
* Mattermost GitLab bot posts the description as is.
* This makes the messages by the  hard to read.

![grafik](https://user-images.githubusercontent.com/495429/120985074-8c14a480-c77b-11eb-81cb-603dabd03cf2.png)

## Solutions

* Remove all HTML tags from the description.
* Convert all supported HTML tags (`<em>`, `<a>`, `<li>`) to Markdown, and remove all other HTML tags.

**Comment by mickmister** [comment]
Note that this is implemented in the GitHub plugin https://github.com/mattermost/mattermost-plugin-github/pull/464, and the same solution can be applied here.
