### ISSUE TITLE
Remove redundant webhook on a project in different channel

### ISSUE THREAD

**Issue by swicaksono** [mattermost/mattermost-plugin-gitlab#253]
How I can remove a redundant webhook from the same project? I accidentally created a webhook after subscribing to a GitLab project that already created its webhook in a different channel. So if there is an event in the project GitLab it will notif the trigger double in the channel. 

Many thanks.

**Comment by aaronrothschild** [comment]
At this time, we don't want to risk accidentally deleting a webhook automatically, but it can be reconfigured manually to remove the double notifications.
