### ISSUE TITLE
Invalid scope error during `/gitlab connect`

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-gitlab#257]
A user is getting this error when running `/gitlab connect`:
> The requested scope is invalid, unknown, or malformed

I believe the error is showing in GitLab's interface after the command is run.

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/xi8z5f1cz7fybk71xobdumddka) *by `@rauldipeas`*._

**Comment by almereyda** [comment]
I can confirm that the documentation at https://docs.mattermost.com/onboard/sso-gitlab.html reads to

> c. Do not select any options under **Scopes**.

while the GitLab interfaces shows this when trying not to set any scopes:

![Screenshot 2021-11-25 at 04-41-27 Applications · User Settings](https://user-images.githubusercontent.com/1645308/143375935-b8e95025-10c5-4bb3-9685-6ff39d53753f.png)

**Comment by sibasankarnayak** [comment]
@dipak-demansol can you try to reproduce this issue and let me update on this ?

**Comment by dipak-demansol** [comment]
@sibasankarnayak issue regenerated, **if the user forgot to select "api" or "read_user" Scopes then User will get that  error as "The requested scope is invalid, unknown, or malformed.", Both scopes are mandatory.**
https://user-images.githubusercontent.com/89907719/162615875-e02510f3-2644-48e5-b321-06239fe22dd6.mov

**Comment by kc9jud** [comment]
This is still a (security) issue. 
![image](https://user-images.githubusercontent.com/4133644/203711165-35a5f241-ecb5-4c23-8ab6-978efde78001.png) 
It looks like #292 would fix this.

**Comment by binaryfire** [comment]
Just encountered this issue too. I'm running the latest Docker versions of Mattermost Team Edition and Gitlab CE.

It seems like the [docs](https://docs.mattermost.com/onboard/sso-gitlab.html) are incorrect:

> Select scopes.
> 
> For Mattermost Team Edition, select read_user.
> 
> For Mattermost Enterprise, select openid, profile, and email.

Are there plans to change this so selecting "api" isn't necessary? Granting Mattermost full read/write API access to the entire Gitlab instance is a major security hole.

**Comment by binaryfire** [comment]
@mickmister Sorry, I didn't notice this was in the plugin repo! Will do.

**Comment by raghavaggarwal2308** [comment]
@mickmister I don't think there is anything we need to do in this issue because the error is caused due to invalid user input. Can you please close this issue if possible?

**Comment by mickmister** [comment]
Sure let's close the issue. Thanks @raghavaggarwal2308
