### ISSUE TITLE
add /gitlab subscriptions to a milestone

### ISSUE THREAD

**Issue by mihai-satmarean** [mattermost/mattermost-plugin-gitlab#270]
very good plugin and very useful, 
for our workflow would be great if you could  
add /gitlab subscriptions to a milestone

**Comment by ashutosh887** [comment]
I would like to work on this @mickmister

**Comment by Kshitij-Katiyar** [comment]
@mickmister I don't think GitLab provides milestones as a trigger for webhooks. And without that, I am afraid we can develop this feature.
