### ISSUE TITLE
Refresh OAuth token

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-gitlab#275]
Starting with GitLab 15.0.0 OAuth token will always expire after 2 hours. Currently the plugin handles oauth token as static data, which they won't be any longer.

Related GitLab issue: https://gitlab.com/gitlab-org/gitlab/-/issues/340848

**Comment by sakaipb** [comment]
I have solved this problem, can I try to submit the code?

**Comment by hanzei** [comment]
Surely, that would be amazing, thanks @sakaipb :tada:

**Comment by DHaussermann** [comment]
@dipak-demansol note that I believe this to be the same issue you found today. It is coincident with intances similar to the following occurring in the server logs at the time
```
{"timestamp":"2022-02-24 16:15:21.937 Z","level":"error","msg":"unable to list merge-request where assignee in GitLab API","caller":"app/plugin_api.go:928","plugin_id":"com.github.manland.mattermost-plugin-gitlab","err":"GET https://gitlab.com/api/v4/merge_requests: 401 {error: invalid_token}, {error_description: Token is expired. You can either do re-authorization or token refresh.}"} 
```

**Comment by dipak-demansol** [comment]
@hanzei FYI :- In The Gitlab `https://gitlab.com/oauth/applications/`, There is a Setting to "Expire access tokens"

![image](https://user-images.githubusercontent.com/89907719/155982004-fbdce933-2f75-44e8-bd34-1c8e5c30522c.png)

**Comment by hanzei** [comment]
@dipak-demansol That setting will be removed in https://gitlab.com/gitlab-org/gitlab/-/issues/340848.

**Comment by mickmister** [comment]
Hi @sakaipb how are you doing? Are you still interested in submitting your work for this ticket?

**Comment by sakaipb** [comment]
@mickmister 
### at server/api.go 
```
func (p *Plugin) reflashToken(token *oauth2.Token) (*oauth2.Token, error) {
	ctx := context.Background()
	conf := p.getOAuthConfig()
	ts := conf.TokenSource(ctx, token)

	if newToken, err := ts.Token(); err != nil {
		p.API.LogError(">>can't reflash accesstoken", "err", err.Error())
		return nil, err
	} else {
		return newToken, nil
	}
} 
```
### at func (p *Plugin) getUnreads(w http.ResponseWriter, r *http.Request) 
```
if strings.Contains(errRequest.Error(), "invalid_token") {
			////如果token失效，刷新再试
			if token, errToken := p.reflashToken(user.Token); errToken == nil {
				user.Token = token
				if err := p.storeGitlabUserInfo(user); err != nil {
					result, errRequest = p.GitlabClient.GetUnreads(user)
					p.writeAPIResponse(w, result)
					return
				}
			} else {
				p.API.LogError("unable to list unreads in GitLab API", "err", errToken.Error())
			}
		}
```
### at plugin.go ,func (p *Plugin) getGitlabUserInfoByMattermostID(userID string) (*gitlab.UserInfo, *APIErrorResponse)
```
//1. Judge whether the token is expired, and refresh a new accesstoken if it is expired
	oldAccessToken := userInfo.Token.AccessToken

	if tok, err := p.reflashToken(userInfo.Token); err != nil {
		p.API.LogError(">>userInfo.Token.AccessToken", "Err", err.Error())
	} else {
		userInfo.Token = tok
	}

	//2. Tokon is refreshed and needs to be saved
	if oldAccessToken != userInfo.Token.AccessToken {
		if err := p.storeGitlabUserInfo(&userInfo); err != nil {
			p.API.LogError("can't store user info", "err", err.Error())
		}
		p.API.LogInfo(">>Token is changed", "Info", "old:["+oldAccessToken+"] new:["+userInfo.Token.AccessToken+"]")
	}

```

**Comment by sakaipb** [comment]
@mickmister  OK, I'll try

**Comment by benz0li** [comment]
@mickmister Please add this to the next release ([Release v1.5.0](https://github.com/mattermost/mattermost-plugin-gitlab/issues/274)).

**Comment by manojmalik20** [comment]
I've also fixed this issue. Should I write unit tests before submitting a PR?

**Comment by philipreimer** [comment]
> @mickmister Please add this to the next release ([Release v1.5.0](https://github.com/mattermost/mattermost-plugin-gitlab/issues/274)).

Will there be an intermediate `1.4.x` release with a fix for this issue?
If yes, is there an ETA for that?

It appears that the plugin is basically broken now when used with Gitlab 15.0+. I have to run `/gitlab connect` every time I open Mattermost. And if I don't I miss notifications from Gitlab.

Or is there some kind of workaround for this issue?
