### ISSUE TITLE
Add Merge Request Approval Subscription

### ISSUE THREAD

**Issue by shakeandbakebaby** [mattermost/mattermost-plugin-gitlab#282]
When a merge request gets approved it is an indicator to go do something else. This request is for adding the ability to subscribe to merge request is approved or unapproved. Current work around is to have a webhook post the change and not the gitlab mattermost plugin.

**Comment by MatthewDorner** [comment]
I would like to work on this.

**Comment by MatthewDorner** [comment]
The merge request approval and disapproval are still `MergeEvent` type webhook events, so there would be no additional subscription feature. You'd just add the code in `webhook/merge_request.go` to handle the `approved` and `unapproved` actions and generate the correct DM and Channel posts. That sound right?
