### ISSUE TITLE
Support the "Job Hook" event type

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-gitlab#289]
A customer is expecting their pipeline events to be handled by the plugin. We handle the `Pipeline Hook` events, but not the `Job Hook` events. I suspect this is the event that is actually not being handled.

More context here https://community-daily.mattermost.com/core/pl/hdr65wz55jfaukojopxzcggf7o

**Comment by spirosoik** [comment]
@mickmister I have done couple of work for pipelines and jobs I will try to raise a PR on Friday

**Comment by hanzei** [comment]
Closed with https://github.com/mattermost/mattermost-plugin-gitlab/pull/302
