### ISSUE TITLE
Move to gitlab

### ISSUE THREAD

**Issue by manland** [mattermost/mattermost-plugin-gitlab#3]
A plugin of gitlab in github...

Pro :
- integrated ci/cd

Cons : 
- community of mattermost is in github
- all other plugins are in github

**Comment by uhlhosting** [comment]
I do not mind to work with gitlab, github become a standard, not that is better.

**Comment by hanzei** [comment]
@manland Is this a topic any longer?

**Comment by manland** [comment]
No @hanzei you can close it if you want.
