### ISSUE TITLE
New Version 1.5.0 not shown in MM Marketplace

### ISSUE THREAD

**Issue by solick** [mattermost/mattermost-plugin-gitlab#314]
Hi, i don't know the process in detail but I was expecting the version 1.5.0 to be upgradable via MM Marketplace or system console. Is this a bug or are there extra steps needed to have new versions in MM Marketplace?

**Comment by bbodenmiller** [comment]
Noticing same issue

**Comment by hanzei** [comment]
It should be available now. Can you confirm?

**Comment by solick** [comment]
Yes I can confirm, it is available and I was able to upgrade. Thanks
