### ISSUE TITLE
Allow triggering manual jobs via /gitlab command

### ISSUE THREAD

**Issue by Blackclaws** [mattermost/mattermost-plugin-gitlab#319]
One of the big advantages of chatops is that you don't have to leave your chat program to interact with CI pipelines.

While the gitlab integration for mattermost slash commands does offer some help in that regard. It isn't equipped to run manual jobs in a current pipeline. 

What I'd love to see is a message: "Pipeline waiting for manual job: Run (Button)"

**Comment by Kshitij-Katiyar** [comment]
@wiggin77 @Blackclaws 
We currently have a command to trigger pipelines through a slash command i.e 
`/gitlab pipelines run OWNER/REPO BRANCH_NAME`. 
Can you please elaborate on the requirements of this issue?

**Comment by raghavaggarwal2308** [comment]
Closing this as completed for now, can reopen if there are any other requirements
