### ISSUE TITLE
Wrong notification saying "X assigned you to merge request" when the issue is updated (e.g., new commits pushed)

### ISSUE THREAD

**Issue by wkentaro** [mattermost/mattermost-plugin-gitlab#321]
This seems to be a known issue, but can anyone guide me to resolve this?
It is a bit annoying to get notification every time someone pushes a new commit.
![image](https://user-images.githubusercontent.com/4310419/196608475-464ba9c0-aec9-48fd-aa48-f6282262f89f.png)

**Comment by mickmister** [comment]
Hi @wkentaro! It looks like this may be possible via `event.Changes.Assignee.Previous` and `event.Changes.Assignee.Current`. We can diff these two arrays to find if there is a new assignee. Then we can DM the new assignee(s) if there is one. Would you be interested in implementing this?

https://github.com/xanzy/go-gitlab/blob/6da2d13f2241eab2edf52f881b28a31595780a7e/event_webhook_types.go#L557-L561

**Comment by wkentaro** [comment]
Yes, I'm happy to. One thing that is blocking me to do so is that it is not very clear to me if `xxxUsername` variables point the username of Gitlab or Mattermost. (Do you know which is that?)

https://github.com/mattermost/mattermost-plugin-gitlab/blob/1a620e3593d75297d8eaf735bd951194b717ba59/server/webhook/merge_request.go#L23-L24

Looking at the messages, it looks like they are the username of Gitlab.

https://github.com/mattermost/mattermost-plugin-gitlab/blob/1a620e3593d75297d8eaf735bd951194b717ba59/server/webhook/merge_request.go#L32-L37


But these variables are used for sending messages to `ToUsers`
https://github.com/mattermost/mattermost-plugin-gitlab/blob/1a620e3593d75297d8eaf735bd951194b717ba59/server/webhook/merge_request.go#L48-L53

so I wonder if it is also somehow related to the one for Mattermost?

-----

It seems most likely they are the username of Gitlab, so I can do something like below:
```
if authorGitlabUsername in event.Changes.Assignee.Current and \
       authorGitlabUsername not in event.Changes.Assignee.Previous:
   toUsers.append(authorGitlabUsername)
```
but if there's any way to test these. Please let me know.

**Comment by ashutosh887** [comment]
Let me work on this @wkentaro

**Comment by mickmister** [comment]
Hi @ashutosh887, sorry for the late response here. Are you still interested in working on this?

**Comment by mickmister** [comment]
@mkdbns Heads up that a customer has pointed this out, so I'm adding to the plugin maintenance board. Also here's a thread with some discussion on this https://community.mattermost.com/core/pl/bk4z76cqm3dxprcpf536jb3gwr

**Comment by mickmister** [comment]
Note the open PR that is no longer being worked on here https://github.com/mattermost/mattermost-plugin-gitlab/pull/324

**Comment by tschuyebuhl** [comment]
is this still up for grabs?

**Comment by mickmister** [comment]
Indeed it is @tschuyebuhl. Let me know if you'd like to work on it, and I can assign it to you :+1:

**Comment by tschuyebuhl** [comment]
yeah, I would love to work on it if it's not a problem
