### ISSUE TITLE
Unable to determine status of Webhook

### ISSUE THREAD

**Issue by genestouxguy** [mattermost/mattermost-plugin-gitlab#325]
Hi,

When I subscribe with the command `/gitlab subscription add group-test/test-project issues,issue_comments`, I get the response `Unable to determine status of Webhook. See [setup instructions](https://github.com/mattermost/mattermost-plugin-gitlab#step-3-create-a-gitlab-webhook) to validate.`.

But I receive all the issues notification ... 

The link to stepup instruction is dead but I use this docs (https://mattermost.gitbook.io/plugin-gitlab/setup/configurationhttps://mattermost.gitbook.io/plugin-gitlab/setup/configuration)

I setup the GitLab webhook with the url `https://my_mattermost_domain/plugins/com.github.manland.mattermost-plugin-gitlab/webhook`, the secret token come from `my_mattermost_domain -> System Console -> Plugins -> GitLab -> Webhook Secret`.

Did I miss something ?

Thanks !

**Comment by raghavaggarwal2308** [comment]
@genestouxguy Are you still facing the issue or do you need any help here?

**Comment by genestouxguy** [comment]
Hi, sorry I forgot this issue. I can't remember. I close this issue.
