### ISSUE TITLE
Triggering a pipeline does not automatically create a subscription to pipeline events

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-gitlab#341]
Triggering a pipeline does not automatically create a subscription to pipeline events. I don't recall any discussion about this in the feature PR from @spirosoik (I may have missed it) but, I realize now the UI message tells me this has happened.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/35588783/206479076-cdca5818-ecbe-4473-8eac-748981bf758c.png">

A couple points here...
- This would also require the creation of a webhook if none exists (we have a slash command for that so there must be an implemented way to create one via the API already)
- This would be beneficial to GitLab - Playbooks strategic integration.

**Comment by DHaussermann** [comment]
@spirosoik you are correct. As per other plugins - I would not expect that a subscription would be automatically created. I only raise this as an issue because the UI post message tells me a subscription was created.

I can adjust the label for the time being and will post in the Mattermost channel.

One additional point - In the context outside of Playbooks this feature has added complexity. The channel may contain a subscription for that project already. In such a case, the feature list would need to be preserved so, this would become a bit more complex.

**Comment by DHaussermann** [comment]
@lieut-data and @spirosoik - I think we all agree that this is a suitable feature improvement for the future. 

However - I'm staring release testing now for GitLab `v1.6.0` and realized the problematic line of text is still in the UI
![image](https://user-images.githubusercontent.com/35588783/211660759-ac218064-3ca8-4301-9f93-7031f8cf4449.png)

Can we quickly remove this line as the feature does not exist yet?

**Comment by lieut-data** [comment]
For sure, @DHaussermann! See linked PR above.

**Comment by Kshitij-Katiyar** [comment]
@mickmister @DHaussermann `/gitlab pipeline run owner/repo branch` command is specific to a branch but `/gitlab subscription owner/repo pipeline` is not specific to a branch. We can create a subscription automatically after running the pipeline command but it will not be specific to the branch instead it will send a notification related to the pipeline of all the branches present in the repo. Do you want me to work on it?

**Comment by spirosoik** [comment]
@Kshitij-Katiyar I like the idea. @mickmister any input here?

**Comment by mickmister** [comment]
@Kshitij-Katiyar @spirosoik I'm always weary of "automatic actions" when performing something somewhat related. Adding a subscription isn't necessarily destructive so not a huge deal, but I would prefer to have an ephemeral interactive message show that says "This channel is currently not subscribed to (repo). Would you like to create a subscription for this channel?" Then the admin just needs to click a button in the message to create the subscription.

We would need to take into account any parameters they want to set in the subscription though. Maybe we instead give them a command to run and they can customize the command to configure the subscription that way.

**Comment by mickmister** [comment]
Not sure exactly how to handle the "specific branch" case. If we don't support subscriptions for specific branches already, it seems like an unrelated point to me

**Comment by Kshitij-Katiyar** [comment]
> Not sure exactly how to handle the "specific branch" case. If we don't support subscriptions for specific branches already, it seems like an unrelated point to me

@mickmister Yeah, I thought we were running a pipeline for a particular branch, and then the user should only get notifications about the pipelines of this branch. But we can send a message to the user stating that they can create the subscriptions if a subscription doesn't exist already.

**Comment by raghavaggarwal2308** [comment]
@mickmister How should we proceed on this issue?
Should we send a message to the user containing the command for creating the subscription if it doesn't already exist? Or is there anything else we need to add?

**Comment by mickmister** [comment]
@raghavaggarwal2308 Yeah an ephemeral message sounds good. If we already have slash commands to do all the followup operations, then I suggest we respond with some short instructions on what commands to run
