### ISSUE TITLE
Intermittent issue where subscription deletes don't reflect on RHS in real time.

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-gitlab#342]
When deleting a subscription a "refresh" event such as a channel change or RHS open / close must occur for the newly deleted subscription to no longer show. (Using the add command to change the feature list of an existing subscription does update in real time.

I've seen this before but did not repro when investigated. 
Unfortunately I see nothing of interest in the dev console  

https://user-images.githubusercontent.com/35588783/206579838-539c9738-c3c6-41fc-9902-e7e294147647.mov

Best chance for investigation may be to stop touching the affected server and invite dev to see if they can observe the issue.

**Comment by lieut-data** [comment]
@DHaussermann, can you monitor the active websocket connection for events after triggering the delete? 

<img width="619" alt="image" src="https://user-images.githubusercontent.com/1023171/207150548-15d12ac0-d216-4259-b979-f7ff3ed6cbce.png">

I'd like to see if the event is even coming down from the server.

**Comment by DHaussermann** [comment]
@lieut-data the WS event does show when the delete is attempted.
Here is a recording of me capturing the event and the data it provided

https://user-images.githubusercontent.com/35588783/207227735-a26b4f8c-f108-4739-b4cb-1585361e02a8.mov


```
{event: "custom_com.github.manland.mattermost-plugin-gitlab_gitlab_channel_subscriptions_updated",…}
broadcast
: 
{omit_users: null, user_id: "", channel_id: "w9t6sprkqirztm6owkefqqhtgh", team_id: "",…}
channel_id
: 
"w9t6sprkqirztm6owkefqqhtgh"
connection_id
: 
""
omit_connection_id
: 
""
omit_users
: 
null
team_id
: 
""
user_id
: 
""
data
: 
{,…}
payload
: 
"{\"channel_id\":\"w9t6sprkqirztm6owkefqqhtgh\",\"subscriptions\":[{\"repository_name\":\"dhaussermann/pipelinetest\",\"repository_url\":\"https://gitlab.com/dhaussermann/pipelinetest\",\"features\":[\"merges\",\"issues\",\"tag\"],\"creator_id\":\"i77ghs7jypb7bgwuhg8uox5ana\"}]}"
event
: 
"custom_com.github.manland.mattermost-plugin-gitlab_gitlab_channel_subscriptions_updated"
seq
: 
9
```

**Comment by lieut-data** [comment]
Fascinating: so the webapp is functioning correctly: essentially, the server is sending back a stale list of subscriptions, instead of an empty list in this case with the subscription removed.

At the code level, it just amounts to a `KVSet(); KVGet()` between the delete and broadcast, so if the latter isn't returning the former, I'm guessing we have a synchronization issue between the master and replica.

I can apply a workaround given we /know/ we just deleted this subscription, but I'm curious if we've run into this with other plugins? cc @mickmister

**Comment by mickmister** [comment]
@lieut-data We have indeed run into this with other plugins. On a framework level, we have discussed having something like a write-through cache used during the duration of a user's request, but that would require a lot of changes and would potentially be error prone.

At the moment, the plugin does need to take KV store data mutations into account when using `KVGet` in the same request.
