### ISSUE TITLE
Subpath server is missing GitLab icons on Upgrade

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-gitlab#343]
I see an issue on the subpath server where the GitLab icon is missing after the upgrade.
![image](https://user-images.githubusercontent.com/35588783/206580644-8b24323d-c331-4e10-a488-7fac907fa4ff.png)

0/5 this may be a subpath specific issue. I've not see it on other servers only here https://subpath.test.mattermost.com/mattermost  
![image](https://user-images.githubusercontent.com/35588783/206580522-905a9442-1f2f-4b14-af3c-5e8f5d6318da.png)
0/5 This 2nd screen seems to show it's trying to fetch from a relative path and failing.

**Comment by lieut-data** [comment]
@DHaussermann, can you share the link to that subpath instance? From the screenshot, it looks like Playbooks is affected as well (but not Boards), so I'd like to understand where the issue is potentially across multiple products.

**Comment by DHaussermann** [comment]
@lieut-data there is an invite link here https://subpath.test.mattermost.com/mattermost/signup_user_complete/?id=hzzfk8adk7by3ptwmxatu5ogpc&sbr=sa

Please ping me if you need an account promoted.

**Comment by lieut-data** [comment]
Thanks, @DHaussermann! Do you recall what I need to do as a user to get the apps bar enabled? 
<img width="843" alt="image" src="https://user-images.githubusercontent.com/1023171/207664185-747eeec5-3da7-425d-931b-e23dccb7c3a4.png">

**Comment by DHaussermann** [comment]
@lieut-data I have enabled it for you here 
![image](https://user-images.githubusercontent.com/35588783/207664664-131c4c41-cd54-41c5-af4f-d0b4a32fefb3.png)


Not that the config may roll back to know state nightly on some of these test servers.

Let me know if you have any issue uploading or enabling the plugin via the sys console (Or if you want me to re-upload the build from this brach I compiled locally)

**Comment by lieut-data** [comment]
Aha, thanks! Yeah, if not already installed, it would be great to have my credentials boosted to sysadmin so I can iterate here. Thanks, @DHaussermann!

**Comment by DHaussermann** [comment]
@lieut-data the server restores it config nigttly so, I have now re-enabled and configured the plugin so authentication will work. 

I also promoted your user I found 
`@jesse`
Email: `jesse@mattermost.com`

**Comment by lieut-data** [comment]
@DHaussermann, after digging into this for a bit, it seems that `/public` handling for plugins is broken altogether with subpaths. Fix at the server now up at https://github.com/mattermost/mattermost-server/pull/21886.
