### ISSUE TITLE
Unread messages not displaying in plugin 

### ISSUE THREAD

**Issue by emarcanio** [mattermost/mattermost-plugin-gitlab#372]
It seems that the plugin is not picking up the todo items from our gitlab instance. The connection seems to work since when you update MR's the number gets updated but that does not happen with unread messages. When you click on the "Unread messages" icon from the MM plugin it does bring you to the todo list in gitlab with the list of items. Any help with debugging this would be appreciated. 
![image](https://user-images.githubusercontent.com/131918128/234707708-31fa1b85-bc25-4a52-9ec8-59fc7fa7fdc2.png)
![image](https://user-images.githubusercontent.com/131918128/234707815-1ca867a7-ecc4-4218-b049-57c81de24e8e.png)

**Comment by mickmister** [comment]
Hi @emarcanio, thanks for creating this issue. I have a few questions about this:
- What version of GitLab are you using?
- What version of Mattermost, and GitLab plugin are you using?
- Do the unread messages show when you run the `/gitlab todo` command?

**Comment by emarcanio** [comment]
- Version of GitLab - 15.11

- Version of MM plugin - 1.6.0

- When running the `/gitlab todo` command I get the following error. Although I know it is connected because `/gitlab me` shows the correct account attached

![image](https://user-images.githubusercontent.com/131918128/235710894-f35ebb61-01a5-4928-980d-af6a48d70437.png)
 
I am seeing an error in the server log that looks related -
"failed to fetch app bindings","caller":"app/plugin_api.go:970","plugin_id":"com.mattermost.apps""

**Comment by emarcanio** [comment]
Another nasty error we are seeing in the logs - 
```
{"timestamp":"2023-05-02 15:53:22.507 Z","level":"warn","msg":"Recovered from a panic","caller":"app/plugin_api.go:979","plugin_id":"com.github.manland.mattermost-plugin-gitlab","url":"/api/v1/unreads","error":"runtime error: invalid memory address or nil pointer dereference","stack":"goroutine 170 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\nmain.(*Plugin).withRecovery.func1.1()\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/api.go:143 +0x74\npanic({0xe17840, 0x1710c00})\n\truntime/panic.go:884 +0x212\ngithub.com/mattermost/mattermost-plugin-gitlab/server/gitlab.(*gitlab).GetUnreads(0xc000354480, {0x11154e8, 0xc0000a56e0}, 0x40?)\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/gitlab/api.go:377 +0x29e\nmain.(*Plugin).getUnreads(0xc00010b520, 0xc0001e3100, {0x11145d8, 0xc00076fd90}, 0xffffffffffffff01?)\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/api.go:522 +0x57\nmain.(*Plugin).attachUserContext.func1({0x11145d8, 0xc00076fd90}, 0xc000525380?)\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/api.go:132 +0x233\nmain.(*Plugin).checkAuth.func1({0x11145d8, 0xc00076fd90}, 0xc00043b300)\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/api.go:179 +0x18a\nnet/http.HandlerFunc.ServeHTTP(0xc0000cd030?, {0x11145d8?, 0xc00076fd90?}, 0x0?)\n\tnet/http/server.go:2109 +0x2f\nmain.(*Plugin).checkConfigured.func1({0x11145d8, 0xc00076fd90}, 0xc00010b520?)\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/api.go:160 +0x98\nnet/http.HandlerFunc.ServeHTTP(0xf8?, {0x11145d8?, 0xc00076fd90?}, 0xc0005254c8?)\n\tnet/http/server.go:2109 +0x2f\nmain.(*Plugin).withRecovery.func1({0x11145d8?, 0xc00076fd90?}, 0xc00063ef30?)\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/api.go:147 +0x85\nnet/http.HandlerFunc.ServeHTTP(0xc00043b200?, {0x11145d8?, 0xc00076fd90?}, 0xc000060800?)\n\tnet/http/server.go:2109 +0x2f\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc00035a9c0, {0x11145d8, 0xc00076fd90}, 0xc00043b100)\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf\nmain.(*Plugin).ServeHTTP(0xc00010b520, 0xf35c60?, {0x11145d8, 0xc00076fd90}, 0x3?)\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/api.go:37 +0xe5\ngithub.com/mattermost/mattermost-server/v6/plugin.(*hooksRPCServer).ServeHTTP(0xc0000b2260, 0xc0002c67c0, 0x1?)\n\tgithub.com/mattermost/mattermost-server/v6@v6.5.0/plugin/client_rpc.go:456 +0x417\nreflect.Value.call({0xc00007cb40?, 0xc0000ae510?, 0xc000162d80?}, {0xf433ca, 0x4}, {0xc000513ef8, 0x3, 0x203000?})\n\treflect/value.go:584 +0x8c5\nreflect.Value.Call({0xc00007cb40?, 0xc0000ae510?, 0x40d5bf?}, {0xc000513ef8?, 0x8?, 0x7fdc52f64108?})\n\treflect/value.go:368 +0xbc\nnet/rpc.(*service).call(0xc0000b65c0, 0xc00070aa28?, 0xc0000bd100?, 0xc0000c83a0, 0xc00034cd00, 0xc0000b3c80?, {0xd89720?, 0xc0002c67c0?, 0x18?}, {0xd975e0, ...}, ...)\n\tnet/rpc/server.go:382 +0x226\ncreated by net/rpc.(*Server).ServeCodec\n\tnet/rpc/server.go:479 +0x3fe\n"}
```

**Comment by mickmister** [comment]
That nil pointer reference is occurring in the line below. It seems either `todo` or `todo.Project` is nil, most likely `todo.Project`. This seems to imply that there can be a todo in GitLab that is not tied to a given project. Is this the case for one of your todos?

https://github.com/mattermost/mattermost-plugin-gitlab/blob/65187cc3db5861f594e663506185458cadd5347e/server/gitlab/api.go#L377

It seems the panic recovery logic has been added to HTTP endpoints (like the unread notifications endpoint) but not slash command handlers (like `/gitlab todo`). I've made a ticket to fix this https://github.com/mattermost/mattermost-plugin-gitlab/issues/373

**Comment by emarcanio** [comment]
All of my current todos in GitLab are tied to a given project. Thank you for making that issue!

**Comment by mickmister** [comment]
@emarcanio Would you be willing to try running a debug build that may shed some more light on the issue?

**Comment by emarcanio** [comment]
@hanzei Sure! How would I go about applying those changes to my deployment?

**Comment by emarcanio** [comment]
@hanzei So we are running Mattermost on a Kubernetes cluster and do no have a config.json. I have been trying to figure out a way to enable `PluginSettings > EnableUploads` to upload this plugin but am not finding anything straight forward since the docs explain it cannot be edited through UI or REST API. I tried using `mmctl` but I get an error 

``` Changing PluginSettings.EnableUploads is not allowed due to security reasons.```

The only other way I can think of making this change is to update our database configuration table but that would require a script since the current configuration needs to be pulled down and pushed up with the change to save the current settings. Unless you have a recommendation on how to enable that setting I don't think it is feasible to test

**Comment by mickmister** [comment]
@emarcanio You can use the env var `MM_PLUGINSETTINGS_ENABLEUPLOADS=true` https://docs.mattermost.com/configure/environment-variables.html

**Comment by emarcanio** [comment]
Thanks @mickmister, I've enabled that setting but when attempting to upload the file I get an error 
```
Received invalid response from the server.
```
In the logs the error is 
```
"level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","caller":"plu │
│ gin/client_rpc.go:378","plugin_id":"com.github.manland.mattermost-plugin-gitlab","serve_http_stream_id":29,"error":"timeout waiting for accept"
```

**Comment by mickmister** [comment]
@emarcanio Are there any additional logs if you set the log level to `DEBUG` (either `LogSettings.ConsoleLevel` or `LogSettings.FileLevel` depending on how you're viewing your logs)

**Comment by bbodenmiller** [comment]
@hanzei any ideas when this may be released?

**Comment by hanzei** [comment]
@DHaussermann and I are working on a release. But there is no ETA.
