### ISSUE TITLE
Trigger types available in Gitlab not mapped to the plugin?

### ISSUE THREAD

**Issue by N0K0** [mattermost/mattermost-plugin-gitlab#387]
Hey! Looking over the event types in GitLab, I get a feeling some are missing from the plugin?
![image](https://github.com/mattermost/mattermost-plugin-gitlab/assets/13900053/c88d565e-8efa-49fc-a0e4-f3e0dd1c9651)

Namely, Release and Deployments would be super to have access to also :)

**Comment by raghavaggarwal2308** [comment]
@wiggin77 Do you think we should pick up this task? It is a feature request and will take some time to implement as we will have to handle multiple cases.

**Comment by raghavaggarwal2308** [comment]
@wiggin77 Gentle reminder for this

**Comment by wiggin77** [comment]
@raghavaggarwal2308 , yes this is green-lit.
