### ISSUE TITLE
Connecting to GitLab is failing from Mattermost desktop

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-gitlab#398]
Due to a change on GitLab's side (possibly related to Cloudflare - connecting to GitLab with the Mattermost desktop client is no longer working.

When you click the connection link, the modal opens but the spinner for `Checking if the site connection is secure` never stops and then the connection attempt eventrually times out.   
![image](https://github.com/mattermost/mattermost-plugin-gitlab/assets/35588783/3d18aac2-297e-43ae-b66b-33a4e289e54e)

This is **not** a regression from the previous `1.6.0` release. The same behavior will occur there as well.

**Note**: Using Chrome or other browsers is not affected.

Steps:
- Install and enable the plugin
- Configure an oAuth app on GitLab side (or use Chimera)
- Run the `/gitlab connect` command and click the link

**Comment by DHaussermann** [comment]
@mickmister I'm unsure of the current triage process but, I have added the label. Please make any other changes needed to this issue.

**Comment by raghavaggarwal2308** [comment]
@mickmister I explored this issue. I think the issue is occurring while Cloudflare is trying to verify the site's security. So, we can't do anything on our end as this has something to do with the GitLab integration with Cloudflare.
We can try to open the connect URL in the browser of the user instead of the desktop app. Should we try and do that?

**Comment by mickmister** [comment]
> We can try to open the connect URL in the browser of the user instead of the desktop app. Should we try and do that?

@raghavaggarwal2308 Have you confirmed that this consistently works in browser, but not the desktop app?

If we automatically open the link in the browser from desktop app, I believe the user will need to sign into Mattermost again in the browser. We had a similar issue in the Jira plugin related to using the desktop app, so we prompted the user to use the browser instead when they tried to connect in the desktop app. This may be a viable solution here. We would want to make sure we cover all of the cases where we connect the user's account.

https://github.com/mattermost/mattermost-plugin-jira/blob/06a02e8722901d53be4edec9b2bed39314bf9147/webapp/src/actions/index.ts#L412-L416

**Comment by raghavaggarwal2308** [comment]
@mickmister Yes, it works fine in the browser. Should we go ahead with this approach? Also, what cases are you talking about here?

**Comment by mickmister** [comment]
> Should we go ahead with this approach?

@raghavaggarwal2308 Yes I think so

@devinbinnie Any ideas on if we can make this work in the desktop app? Essentially there's some check that CloudFlare is doing when the user tries to log into GitLab using a popup in the desktop app, and it gets stuck here (see image in ticket description). Any advice on how to debug this further with the desktop app?

> Also, what cases are you talking about here?

Any case that would open up the user connect dialog. We should make the UX of telling the user "Please use the browser" to be as user-friendly as possible. Can it go in the dialog itself?

**Comment by devinbinnie** [comment]
@mickmister You'll want to turn on Debug logging in the Settings Window, and there should be some nice information in the logs around what navigation is being blocked. My guess is that it's right to shoot out to CloudFlare before we expect it to.

If you don't see anything, ping me and I'll see if I can reproduce the issue.

**Comment by raghavaggarwal2308** [comment]
>Any case that would open up the user connect dialog. We should make the UX of telling the user "Please use the browser" to be as user-friendly as possible. Can it go in the dialog itself?

@mickmister I don't think we can display the message in the dialog. We were thinking of sending an ephemeral message to the users whenever they run the "connect" command in the desktop app asking them to log in to Mattermost in a browser and connect their Gitlab account from there. What are your thoughts on this?

**Comment by mickmister** [comment]
@raghavaggarwal2308 Yep sounds good to me :+1:
