### ISSUE TITLE
Create issues through slash commands

### ISSUE THREAD

**Issue by Rulqu** [mattermost/mattermost-plugin-gitlab#402]
Could we have issue creation through slash commands like Slack has?https://docs.gitlab.com/ee/user/project/integrations/gitlab_slack_application.html#slash-commands

**Comment by miukumac** [comment]
+1. Being able to create new issues via chat is an extremely important and a lacking feature.

**Comment by linus-ha** [comment]
I've seen other integrations in other environments (slack and Jira or something like that) where you could add a Ticket reaction (🎫) on the message you want to convert to an issue. The bot would answer with the issue link, where the issue contains the original Slack message. 

Something like this would be very helpful.

**Comment by linus-ha** [comment]
Related to https://github.com/mattermost/mattermost-plugin-gitlab/pull/306
