### ISSUE TITLE
Can't fetch token: 401 Unauthorized

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-gitlab#410]
This issue was reported on the community server here https://community.mattermost.com/_redirect/pl/3dgd3smrotngpmukpsftiw1s9a

![image](https://github.com/mattermost/mattermost-plugin-gitlab/assets/6913320/0666ae37-6560-45f1-9a85-7b2ee878d5dd)

**Comment by raghavaggarwal2308** [comment]
Closing this issue as issue reported is not replying anymore. After some exploration, w think the issue might have been caused because of invalid value for client ID in plugin settings. 
Can reopen if someone faces this issue again.
