### ISSUE TITLE
Gitlab OAuth Application secrets are now longer than 64 characters

### ISSUE THREAD

**Issue by stachom** [mattermost/mattermost-plugin-gitlab#412]
Quite recently Gitlab introduced a [change](https://gitlab.com/gitlab-org/gitlab/-/commit/c5d6a3f55ecaef437724495fff7687b968bd25c9) that adds a certain constant prefix ("gloas-") to the OAuth Application Secret they generate. The resulting secret is longer than 64 characters so it is now impossible to fully complete _/gitlab setup_ from mattermost side, because the dialog window checks if the 'client_secret' is exactly 64 characters long. The problem is in the **server/flow.go** file, around line 528. I won't provide an exact patch because I don't know what is the desired behaviour here, anyhow it needs to be fixed.

**Comment by dramirez-qb** [comment]
https://github.com/mattermost/mattermost-plugin-gitlab/blob/master/server/flow.go#L527-L529

**Comment by Entrepreneur-AJ** [comment]
Confirming issue, im having same problem with Gitlab-CE Omnibbus generating a 71 character secret

**Comment by mickmister** [comment]
Hi @stachom @dramirez-qb @Entrepreneur-AJ, thanks for reporting this issue. I've submitted a fix for this here, which removes the check for the length of the secret https://github.com/mattermost/mattermost-plugin-gitlab/pull/419

In the meantime, you should be able to complete the setup process using the documentation in the README here https://github.com/mattermost/mattermost-plugin-gitlab. It is less streamlined than using the `/gitlab setup` flow, but it should still work. Thanks

**Comment by stachom** [comment]
Thanks, @mickmister ! I've tried to follow those instructions earlier and failed, because there is a small error: the first step mentions URL http://gitlab.com/-/profile/applications instead of something like http://gitlab.com/admin/applications. Now it seems to be working fine.
