### ISSUE TITLE
Version 1.8.0 not available in MM Marketplace

### ISSUE THREAD

**Issue by nsteinmetz** [mattermost/mattermost-plugin-gitlab#432]
Hi there,

Release 1.8.0 is not (yet) available via the marketplace - could you please make it available ?

Thanks,
Nicolas

**Comment by nsteinmetz** [comment]
Or should we open the issue on marketplace project ?

https://github.com/mattermost/mattermost-marketplace/

**Comment by mickmister** [comment]
Hi @nsteinmetz, apologies for the late reply. This is now available in the marketplace per https://github.com/mattermost/mattermost-marketplace/pull/409

**Comment by nsteinmetz** [comment]
Thanks @mickmister 👍
