### ISSUE TITLE
How to delete duplicates webhook ?

### ISSUE THREAD

**Issue by momala454** [mattermost/mattermost-plugin-gitlab#447]
I've run multiple times the command webhook add by mistake, now it's sending every notification multiple times.
How do I remove the duplicates ?

**Comment by mickmister** [comment]
Hi @momala454, thanks for filing this issue. This command creates a webhook on GitLab's side, so you will need to go into GitLab's UI and delete the webhook from there. Please let me know if you are able to resolve this on your end. Thanks

**Comment by momala454** [comment]
thanks you it works
