### ISSUE TITLE
You don't have the permissions to create subscriptions for this project

### ISSUE THREAD

**Issue by alekseyp** [mattermost/mattermost-plugin-gitlab#493]
Hello,

Plugin version: GitLab version: 1.9.0, [191a11a](https://github.com/mattermost/mattermost-plugin-gitlab/commit/191a11a9b91c308d9613f9d13a12dbe330de6b2d), built Fri, 19 Apr 2024 17:24:08 UTC with go1.21.9

I'm the owner of the group and I'm the owner of the project.

When I'm subscribing to a group or a project I'm getting: `You don't have the permissions to create subscriptions for this project`

Here is the log:

```
==> current <==
2024-05-07_19:58:19.29204 {"timestamp":"2024-05-07 19:58:19.291 Z","level":"warn","msg":"You don't have the permissions to create subscriptions for this project.","caller":"app/plugin_api.go:1006","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
```

Here is the list of commands I've tried with the same error message.

```
/gitlab subscriptions add group
/gitlab subscriptions add group/project
/gitlab subscriptions add group/project issues,confidential_issues,merges,tag
/gitlab subscriptions add group/project issues,merges,tag
```

**Comment by alekseyp** [comment]
Looks like the bug was introduced in 1.9.0, since it's been a week with no notifications even on subscribed channels for us.

For anyone looking for a temp fix:
 - reupload the 1.8.1 plugin
 - re-save "Enable Private Repositories" setting.

**Comment by apollo13** [comment]
I have the same issue, the workaround works. Thank you!

**Comment by LotusMoves** [comment]
i can confirm this is broken this appears to be what broke it I am unsure how to test it locally [54a9c46 ](https://github.com/mattermost/mattermost-plugin-gitlab/commit/54a9c4654f1400358051db9aa326cf6c684494f2)

**Comment by mickmister** [comment]
Thanks all. We'll be releasing a fix for this shortly. Will follow up here with me more info as it comes. Thanks so much

**Comment by mickmister** [comment]
A release with the fix is available here https://github.com/mattermost/mattermost-plugin-gitlab/releases/tag/v1.9.1, and will be in the marketplace early next week
