### ISSUE TITLE
Wrong link to GitLab Documentation in Mattermost

### ISSUE THREAD

**Issue by sudo-debug** [mattermost/mattermost-plugin-gitlab#501]
The link to the gitlab documentation is wrong leading to the startpage (fallback) of mattermost docs.

https://github.com/mattermost/mattermost-plugin-gitlab/blob/28ca0719053cfb8e5003a4b9aa4d2a27081a2e1b/README.md?plain=1#L18

Correct would be https://docs.mattermost.com/integrate/gitlab-interoperability.html

**Comment by mickmister** [comment]
Hi @sudo-debug, thanks for catching this and filing this issue. @raghavaggarwal2308 I'm thinking this typo may be present in other projects as well

**Comment by raghavaggarwal2308** [comment]
> Hi @sudo-debug, thanks for catching this and filing this issue. @raghavaggarwal2308 I'm thinking this typo may be present in other projects as well

@mickmister Sure, we will look into this
