### ISSUE TITLE
Backport github plugin improvements

### ISSUE THREAD

**Issue by manland** [mattermost/mattermost-plugin-gitlab#61]
- [ ] https://github.com/mattermost/mattermost-plugin-github/pull/103
- [ ] https://github.com/mattermost/mattermost-plugin-github/pull/170
- [ ] https://github.com/mattermost/mattermost-plugin-github/pull/123
- [ ] https://github.com/mattermost/mattermost-plugin-github/pull/137
- [ ] https://github.com/mattermost/mattermost-plugin-github/pull/258

**Comment by hanzei** [comment]
@hanzei to update the list
