### ISSUE TITLE
Refresh icon visibility

### ISSUE THREAD

**Issue by uhlhosting** [mattermost/mattermost-plugin-gitlab#63]
On the 
<img width="80" alt="image" src="https://user-images.githubusercontent.com/6324047/59067107-0f5f3f00-88b1-11e9-9eec-f9c7a02047ef.png">  image is github plugin showcase, here is the gitlab plugin:

<img width="104" alt="image" src="https://user-images.githubusercontent.com/6324047/59067188-3b7ac000-88b1-11e9-83bc-bb8bfd92dd32.png">

Also on macOS app, there are glitches on right side next to slider, when hovering over the gitlab icons.

**Comment by AbhishekTiwari23** [comment]
Can I work on this?
