### ISSUE TITLE
Subgroups support

### ISSUE THREAD

**Issue by djphoenix** [mattermost/mattermost-plugin-gitlab#65]
What about support for subscriptions on entire subgroups or subgroup projects?

**Comment by manland** [comment]
Good point! I need to see if I can incorporate it in !15

**Comment by levb** [comment]
@manland are you intending to work on this feature, or should we make this as an "Up for grabs" ticket?

**Comment by manland** [comment]
@levb you can add an "Up for grabs" label, it's not directly linked to #99 and can be made independently.

**Comment by kop** [comment]
I'll take this one.
