### ISSUE TITLE
Caching in ci doesn't work

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-gitlab#71]
On issue with this setup is that the caching doesn't work. The orb expects the `go.mod` file to be at `/go.mod`. But in this project it's at `/server/go.mod`.
I see 
![Screenshot from 2019-06-24 07-45-29](https://user-images.githubusercontent.com/16541325/59994440-20030980-9654-11e9-9c82-f85499c2ade0.png)

Possible options:
1. Ignore this problem
2. Move `go.mod` into the root directory
3. Modify the orb to make this customizable

@manland Thoughts on this?

_Originally posted by @hanzei in https://github.com/mattermost/mattermost-plugin-gitlab/pull/69#issuecomment-504924341_

**Comment by manland** [comment]
I :+1: to be like other plugins! If others have go.mod at root instead of server I'm ok to move it ;)

**Comment by hanzei** [comment]
Should I or do you want to take care of this?

**Comment by manland** [comment]
Yes you should go for it, you seams to be on steroids tonight! I can't stop you 😁 ! And thanks for you help!
