### ISSUE TITLE
Configuration change must propagate to client side

### ISSUE THREAD

**Issue by manland** [mattermost/mattermost-plugin-gitlab#74]
## Reproduction

* I activate the plugin, default config point to gitlab.com
* A user load MM
* I configure it with my.gilab.com
* User connect to my.gitlab.com but top/left widget point to gitlab.com

## Fix

When OnConfigurationChange in server arrive we must prevent all user connected (web socket) to reload conf

**Comment by manland** [comment]
It seams to be on each first connect.

* User is not logged
* User log
* All icons are linked to gitlab.com instead of private instance
* After f5 links are good and point to private instance

**Comment by larkox** [comment]
May I take this one? First time contributing to plugins, so I may need some extra help 😊

**Comment by manland** [comment]
@larkox yes of course go for it! And ask any question you have here or on https://community.mattermost.com (channel plugin-gitlab or developer-toolkit) ;)
