### ISSUE TITLE
Can't unsubscribe from organization

### ISSUE THREAD

**Issue by paraita** [mattermost/mattermost-plugin-gitlab#79]
Instead of subscribing to a repo I've subscribed to the entire organization. Now I'd like to unsubscribe from the organization because it causes too much noise in our main channel. I can't seem to be able to unsubscribe:

![image](https://user-images.githubusercontent.com/1413759/61756529-199da580-ad58-11e9-8aa7-47cf90728135.png)

I've tried subscribing/unsubscribing from repos and that works, I only seem to get this problem with organizations. Is there a trick to remove that subscription ?

**Comment by manland** [comment]
Hi @paraita thanks to report this issue!

I'm able to reproduce locally. 

@jasonblais @hanzei I'm working on it ;)

**Comment by manland** [comment]
@paraita easy workaround to unblock your instance : `/gitlab unsubscribe addons_odoo//` (yes double /)

The problem is in kvstore we have `addons_odoo/` instead of `addons_odoo` and if you unsubscribe `addons_odoo/` when we clean the name we have `addons_odoo` so double `//` make the job.

**Comment by paraita** [comment]
thank you @manland for the workaround ! We are really enjoying this plugin so far :)
