### ISSUE TITLE
Subscribe to repository with subnamespace

### ISSUE THREAD

**Issue by CarlDemus** [mattermost/mattermost-plugin-gitlab#99]
Hello, 
we using this plugin at our company, we encounter a problem with one of our repository.
This repository have a particularity, it contain a subnamespace.

`/gitlab subscribe owner/repo/subnamespace `return and error : invalid group

**Comment by manland** [comment]
@CarlDemus `subnamespace` is like `group`?

Could be a duplicate of https://github.com/mattermost/mattermost-plugin-gitlab/issues/65?

**Comment by CarlDemus** [comment]
Maybe

**Comment by levb** [comment]
It does appear a duplicate of #65, closing in favor of it.
